architecture: {
    encoder: {
        n_layers: 1,
        n_units: [500],
        distribution: Gaussian
    },
    decoder: {
        n_layers: 1,
        n_units: [200],
        distribution: Bernoulli
    },
    activation: "ReLU"
}

dims: {
    data: 784, # MNIST, flattened
    latent: 10
}

optimization: {
    type: Adam,
    Adagrad_rate: 0.01,
    Adam_rate: 0.01,
    max_grad: 1000000
}

training: {
    batch_size: 1,
    n_iters: 100
}

AEVB: { # Params specified in [1]
    L: 1
}
